# Generated by Django 5.1.2 on 2025-11-02 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('importante', 'Importante'), ('urgente', 'Urgente'), ('info', 'Informativo')], default='normal', max_length=20),
        ),
    ]
