# Generated by Django 5.1.2 on 2025-11-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0002_comunicado_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comunicado',
            name='tipo',
        ),
    ]
