# Generated by Django 5.1.2 on 2025-11-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0003_remove_comunicado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='tipo',
            field=models.CharField(choices=[('urgente', 'Urgente'), ('importante', 'Importante'), ('normal', 'Normal'), ('info', 'Informativo')], default='normal', max_length=20),
        ),
    ]
