# Generated by Django 5.1.2 on 2025-11-05 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0004_comunicado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('licencia', 'Licencia'), ('vacaciones', 'Vacaciones')], default='activo', max_length=15),
        ),
    ]
