# Generated by Django 5.1.2 on 2025-11-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0007_alter_cargo_options_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudpermiso',
            options={},
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='fecha_revision',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='motivo',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='solicitudpermiso',
            name='revisado_por',
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='fecha_revision_direccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='fecha_revision_subdireccion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='revisado_por_direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='solicitudpermiso',
            name='revisado_por_subdireccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='estado',
            field=models.CharField(default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='fecha_solicitud',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='tipo_permiso',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='solicitudpermiso',
            table=None,
        ),
    ]
