# Generated by Django 5.1.2 on 2025-11-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0008_alter_solicitudpermiso_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='documento_respaldo',
            field=models.FileField(blank=True, null=True, upload_to='permisos/'),
        ),
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='tipo_permiso',
            field=models.CharField(choices=[('Administrativo', 'Día Administrativo - Trámites personales'), ('Libre', 'Día Libre - Compensación por horas extras')], max_length=50),
        ),
    ]
