# Generated by Django 5.1.2 on 2025-11-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0009_solicitudpermiso_documento_respaldo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudpermiso',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20),
        ),
    ]
