# Generated by Django 5.1.2 on 2025-11-15 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0010_alter_solicitudpermiso_estado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solicitudpermiso',
            table='solicitud_permiso',
        ),
    ]
