# Generated by Django 5.1.2 on 2025-11-15 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesfam', '0011_alter_solicitudpermiso_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudpermiso',
            name='solicitante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_permiso', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
